### DISCUSSION TITLE
Need help with the Traefik configuration

### DISCUSSION THREAD

**Discussion by johann8** [Ylianst/MeshCentral#4661] [Q&A]
I want to switch from Apache to Traefik. Everything works except file upload. The transfer indicator stops and there are no error messages. It doesn't matter if the fileu is big or small. The transfer does not take place. When I return to Apache, everything works again. Therefore I think that the Traefik configuration is not complete or incorrect. I would appreciate any tips.
Below is configuration:
traefik.yml
```
global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# Log information
# ---
log:
   level: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
   format: common  # common, json, logfmt
   filePath: /var/log/traefik/traefik.log

# Access log
# ---
accesslog:
   format: common  # common, json, logfmt
   filePath: /var/log/traefik/access.log
   filters:
     statusCodes:
       - "400-600"

# Enable API and Dashboard
# ---
api:
  dashboard: true  # true by default
  #insecure: true  # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

# http routing section
# ---
http:

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    secured:
      chain:
        middlewares:
          - secHeaders

### certificate Resolver
# ---
certificatesResolvers:
   production:
     acme:
       email: le@mydomain.de
       storage: /etc/traefik/certs/acme.json
       tlsChallenge: {}
       httpChallenge:
         entryPoint: web
       #dnsChallenge:
         #provider: digitalocean
         #delayBeforeCheck:

providers:
  docker:
    exposedByDefault: false  # Default is true
    endpoint: "unix:///var/run/docker.sock"
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true
```

dynamic_conf.yml
```
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: false   

http:
  middlewares:
    secHeaders:
      headers:
        BrowserXssFilter: true
        ContentTypeNosniff: true
        ForceSTSHeader: true
        frameDeny: true
        STSIncludeSubdomains: true
        STSPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: https
```

docker-compose.override.yml
```
version: "3.7"
services:

  meshcentral:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meshcentral-secure.entrypoints=websecure"
      - "traefik.http.routers.meshcentral-secure.rule=Host(`$HOSTNAME0.$DOMAINNAME`)"
      - "traefik.http.routers.meshcentral-secure.tls=true"
      - "traefik.http.routers.meshcentral-secure.tls.certresolver=production"  # für eigene Zertifikate
      - "traefik.http.routers.meshcentral-secure.service=meshcentral"
      - "traefik.http.services.meshcentral.loadbalancer.server.scheme=http"
      - "traefik.http.services.meshcentral.loadbalancer.server.port=${PORT}"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.meshcentral-secure.middlewares=secHeaders@file"
    networks:
      - proxy

networks:
  proxy:
    external: true
````
.env
```
DOMAINNAME=mydomain.de
HOSTNAME0=mc
REVERSE_PROXY=traefik
PORT=4430
SUBNET=172.26.1
```

Meshcentral config.json
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mc.mydomain.de",
    "WANonly": true,
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "RedirAliasPort": 80,
    "AgentPong": 60,
    "_BrowserPing": 60,
    "BrowserPong": 60,
    "TLSOffload": "traefik",
    "TrustedProxy": ["traefik", "172.26.1.0/24"],
    "WebRTC": true,
    "WebRtcConfig": {
       "iceServers": [
         { "urls": "stun.stun.l.google.com:19302" },
         { "urls": "stun:stun.gmx.de:3478" },
         { "urls": "stun:stun.1und1.de:3478" }
      ]
    },
    "AllowHighQualityDesktop": true,
    "desktopMultiplex": true,
    "DesktopMultiplexor": true
  },
  "domains": {
        "": {
    "title": "REMOTE SUPPORT PORTAL",
    "title2": "WG",
    "minify": true,
    "NewAccounts": "false",
    },
    "agentConfig": [ "webSocketMaskOverride=1" ],
    "certUrl": "https://mc.mydomain.de:443",
    "agentInviteCodes": true
  }
}
```
