### DISCUSSION TITLE
Installing MeshCentral on NAS & Accessing Via TailScale

### DISCUSSION THREAD

**Discussion by otherfutures** [Ylianst/MeshCentral#5824] [Q&A] [answered]
Hello! I'm trying to install MC on my Synology NAS via a docker-compose on Container Manager, but am stuck at trying to access the container. 

I believe this is because the http port redirects to an https port & I don't have a certificate (but I could be wrong--it's my best guess based on the redirection I see in the browser's URL bar & viewing the container logs). 

I don't have a domain hostname, as I have no interest in connecting to WAN & would like to use TailScale to stay in my LAN, so this is where the guides I could find online diverge from me as they all relied on a hostname env in the docker-compose.yml (which I don't have, I think). I did test install on my local machine & was able to access the GUI page (& other abilities) on another machine via TailScale without problem after setting up the agent on the local machine so I feel it's very possible.

This is my docker-compose below based off one I found online (it installs without problem, but I'm unsure how to get access to the GUI via `http://<NAS-IP>:8181` is all--also please note I've gone into MC's `config.json` file & edited `"port"` & `"redirPort"` to 2087 & 8181 respectively as I was running into trouble trying to use the default 443 & 80 ports; going to `http://<NAS-IP>:8181` redirects me to `https://<NAS-IP>:2087`, which I believe is correct but the latter page is unable to connect--I'm also unsure whether my edit to `HOSTNAME` & trying to set to `localhost` instead of a proper DNS is correct or very wrong):

```
version: '3'
services:
  meshcentral:
    restart: always
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 8181:8181 # MeshCentral doesn't like using port 80, but you can by changing the config.json
    environment:
      - HOSTNAME=localhost
      - REVERSE_PROXY=false # set to your reverse proxy IP if you want MC behind a reverse proxy
      # - REVERSE_PROXY_TLS_PORT=
      - IFRAME=true
      - ALLOW_NEW_ACCOUNTS=false # disable self-service creation of new accounts besides admin
      - WEBRTC=false # not officially released, but can work with it. Use with caution
    volumes:
      #config.json and other important files live here. A must for data persistence
      - /volume1/docker/meshcentral/data:/opt/meshcentral/meshcentral-data
      #where file uploads for users live
      - /volume1/docker/meshcentral/user_files:/opt/meshcentral/meshcentral-files
```
