### DISCUSSION TITLE
Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

### DISCUSSION THREAD

**Discussion by bones78** [Ylianst/MeshCentral#5979] [General]
I want to install MeshCentral as a docker image with this yaml:
```
services:
  meshcentral:
    restart: always
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 443:443
      - 80:88
    environment:
      - NODE_ENV=production
      - HOSTNAME=mydomain (Redirection-url to the dynamic ip of my server)
      - USE_MONGODB=false
      - REVERSE_PROXY=false
      - REVERSE_PROXY_TLS_PORT=
      - IFRAME=false
      - ALLOW_NEW_ACCOUNTS=false
      - WEBRTC=false
      - ALLOWPLUGINS=false
      - LOCALSESSIONRECORDING=true
      - MINIFY=true
    volumes:
      - ./meshcentral/data:/opt/meshcentral/meshcentral-data
      - ./meshcentral/user_files:/opt/meshcentral/meshcentral-files
      - ./meshcentral/backup:/opt/meshcentral/meshcentral-backups
      - ./meshcentral/web:/opt/meshcentral/meshcentral-web
```
I get this error:
Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
I use on the same server Adguardhome. What can I do to use MeshCentral also on this server?

**Expected behavior**
Working MeshCentral

**Server Software (please complete the following information):**
 - OS: Ubuntu Server 22.04
 - Virtualization: Docker
 - Network: Adguard home on the same server
 - Version: [e.g. 1.0.43]
 - Node: [e.g. 18.4.0]
