### DISCUSSION TITLE
Raspberry pi 5 (arm64) desktop and terminal tabs not showing

### DISCUSSION THREAD

**Discussion by tobias-carlbom** [Ylianst/MeshCentral#6069] [Issues]
Hi,

I have tried to install meshagent arm and arm64 seperatly on my raspberry pi 5. The installation seem to work fine. Although when the service start i get 15-20 disconnections and connections within 5 seconds. After that the device shows as online in the meshcentral server, but i dont see the Desktop and the Terminal tab. 
Web-vnc and web-rdp does not work either.

Has anyone else had the same problem?

**Comment by silversword411** [comment]
Search issues for Weyland workaround 

Should be added to FAQ

**Comment by si458** [comment]
what OS are you running on the pi 5?
you might not see the desktop tab IF you are using wayland rather than X11,
but that wouldnt explain why you dont see the Terminal tab?
have u tried a fresh install of your OS ?

**Reply by zohaib09** [reply]
@si458 

Sir i am running meshcentral on docker with following docker compose :

```

serverSDC@sdcompaniesRP5:~/meshcentroal $ cat docker-compose.yml 
services:
  meshcentral:
    image: ghcr.io/ylianst/meshcentral:latest
    restart: unless-stopped # <-- This makes it start automatically after reboot
    environment:
      - DYNAMIC_CONFIG=false # Show the option but disable it by default, for safety.
      - HOSTNAME=sdc-macchin3.duckdns.org # Set the hostname in the config.json
      - ALLOW_NEW_ACCOUNTS=false # Disable creation of new accounts (except for the first user) in the config.json
      - USE_MONGODB=false # Enable the Mongo connector in the config.json
      # MONGO_URL=mongodb://username:password@mongodb:27017/meshcentral # Example MONGO_URL
    volumes:
      - /usb_raid/meshcentral/data:/opt/meshcentral/meshcentral-data
      - /usb_raid/meshcentral/user_file:/opt/meshcentral/meshcentral-files
      - /usb_raid/meshcentral/backup:/opt/meshcentral/meshcentral-backups
      - /usb_raid/meshcentral/web:/opt/meshcentral/meshcentral-web
    ports:
      - "800:80"
      - "4430:443"
      - "4434:4434"
```

cofig,json:

```
serverSDC@sdcompaniesRP5:~/meshcentroal $ cat /usb_raid/meshcentral/data/config.json 
{
  "settings": {
    "AllowHighQualityDesktop": true,
    "cert": "sdc-macchin3.duckdns.org",
    "_SelfUpdate": true,
    "minify": true,
    "Port": 443,
    "RedirPort": 80,
    "SessionKey": "<randomstrongstring>",
    "ExactPorts": true,
    "WebRTC": true,
    "DesktopMultiplex": true,
    "UserWebRTC": true,
    "novnc": true,
    "allowDeviceDelete": true,
    "relayPort": 4434
  },
  "domains": {
    "": {
      "title": "Mesh",
      "newaccounts": false,
      "certUrl": "https://sdc-macchin3.duckdns.org/",
      "admin": [
        "admin"
      ]
    }
  }
}
```

On same meshcentral host (PI 5) i installed meshagent. It works but frequently disconnects too. 


```

serverSDC@sdcompaniesRP5:~/meshcentroal $ uname -m
aarch64
```
serverSDC@sdcompaniesRP5:~/meshcentroal $ 

someone suggested to do arm_64bit=0 /boot/firmware/config.txt. is this correct to solve?

Here is the link who suggested for it

https://www.reddit.com/r/MeshCentral/comments/13ucl1h/issues_running_agent_on_raspberry_pi/
