### DISCUSSION TITLE
Cloudflare + reverse proxy (Caddy)?

### DISCUSSION THREAD

**Discussion by Pshemas** [Ylianst/MeshCentral#6173] [General]
I wonder whether anyone of you had set up MeshCentral with Cloudflare AND reverse proxy such as Caddy. If you did - how does the config look like? I'm having issues figuring it out.

The idea is to install MeshCentral via Docker / Podman, with Caddy2 (built with Cloudflare plugin) in another container serving as reverse proxy for all the containers. At the same time subdomain for MC is on Cloudflare with `Proxied` set to `on`.

**Comment by Pshemas** [comment]
ok, so it looks I can't even set it up to work behind Caddy only. I disabled Cloudflare Proxy.  I get `ERR_TOO_MANY_REDIRECTS` now.

Caddy and MeshCentral are both running in containers.

My `config.json` looks like this (redacted a bit):

```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "Cert": "mesh.mydomain.site",
    "Port": 443,
    "TLSOffload": "caddy",
    "WebRTC": true
  },
  "domains": {
    "": {
      "NewAccounts": true,
      "certUrl": "https://caddy:443"
    }
  }
}
```

here's `compose.yaml`:

```
---
services:
  caddy:
    image: caddy-cloudflare
    name: caddy
    restart: always
    env_file:
      - $PWD/.ENV/.caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:z
      - $PWD/site:/srv:z
      - $PWD/caddy_data:/data:z
      - $PWD/caddy_config:/config:z
    networks:
      - caddynet

  meshcentral:
    restart: always
    container_name: meshcentral
    name: meshcentral
    image: ghcr.io/ylianst/meshcentral:latest
      #    env_file:
      #      - /home/uslugi/.ENV/.mc
    volumes:
      - $PWD/meshcentral/data:/opt/meshcentral/meshcentral-data:z
      - $PWD/meshcentral/user_files:/opt/meshcentral/meshcentral-files:z
      - $PWD/meshcentral/backup:/opt/meshcentral/meshcentral-backups:z
      - $PWD/meshcentral/web:/opt/meshcentral/meshcentral-we:z
    networks:
      - caddynet

  helloworld:
    image: nginxdemos/hello
    restart: always
    name: helloworld
    networks:
      - caddynet


networks:
  caddynet:
    name: caddynet
    driver: bridge
...
```

I'm running it via Podman (tried Docker, but it didn't get me any farther) - had some issues with tags when running via `compose` hence extra `name` fields (which would probably make it fail on Docker).

You may notice I also start a simple demo - just to check whether I can actually reverse proxy anything and just to check I'm not just nuts ;) .

Here's Caddyfile:

```
demo.site {
    header {
	X-Robots-Tag "none"
	-Server
    }
    tls {
	dns cloudflare {env.CF_API_TOKEN}
	resolvers 1.1.1.1
    }
    reverse_proxy helloworld 
}

mesh.mydomain.site {
    header {
	X-Robots-Tag "none"
	-Server
    }
    reverse_proxy meshcentral
}
```

**Reply by si458** [reply]
from the looks of it, you have set tlsoffload which is correct, so you need to tell caddy to visit http://meshcentral:443

where as from again the looks of it caddy is trying to visit http://meshcentral which is then being redirected to https://meshcentral which in turn is redirected to http://meshcentral which in turn redirects to https://meshcentral and so on and so on, so its doing a loop and getting stuck

i dont use caddy so im only guessing you need to change `reverse_proxy meshcentral` to something else and make sure its visiting http://meshcentral:443

**Comment by Pshemas** [comment]
thank you si458. Is there a way to set MeshCentral so it would be something like http://meshcentral:4430 or anything else? When I try `http://meshcentral:443` I get `conflicting scheme` error from Caddy.

**Reply by si458** [reply]
try this for your meshcentral config
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "Cert": "mesh.mydomain.site",
    "port": 4430,
    "aliasPort": 443,
    "redirPort": 800,
    "redirAliasPort": 80
    "TLSOffload": "caddy"
  },
  "domains": {
    "": {
      "NewAccounts": true,
      "certUrl": "https://mesh.mydomain.site:443"
    }
  }
}
```
you basically set `port` and `redirport` to whatever ports meshcentral will listen on (dont use 80/443 for example)
then you set `aliasport` and `rediraliasport` to 80/443 so meshcentral knows WHAT port to tell your internet devices to connect back to meshcentral on

you then need to tell caddy to connect to http://meshcentral:4430 (NOT HTTPS!) because the tls is offload to your reverse proxy caddy instead

**Comment by Pshemas** [comment]
Ok, got it - it's why there's a setting for `Port` and `AliasPort`. Now it makes sense :) . So I've been able to get to the admin panel. Will need to check whether with this config agent works. If it does I'll try turning CLoudflare on.

At this point the Caddyfile on my end looks like this:

```
mesh.mydomain.site {
    header {
	X-Robots-Tag "none"
	-Server
    }
    reverse_proxy http://meshcentral:4430
}
```

**Reply by si458** [reply]
dont forget to add `trustedProxy: "cloudflare"` next to `port` and `aliasport` if you use cloudflare,
this tells meshcentral to trust their ip ranges so it can get the remote agents correct IP addresses

p.s. you might also need to set `trustedProxy: "caddy"` too, so meshcentral again knows any connections from caddy is proxied and to get the remote agents correct ip addresses from the headers

otherwise all agent ip addresses would show as your reverse proxy ip address rather than the clients external ip addresses

**Comment by Pshemas** [comment]
You rock!
So I got it fully working (at least it seems so ;) ). My config looks like this:

```json
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "Cert": "mesh.mydomain.site",
    "Port": 4430,
    "AliasPort": 443,
    "TLSOffload": "caddy",
    "trustedProxy": "caddy, cloudflare",
    "WebRTC": true
  },
  "domains": {
    "": {
      "NewAccounts": true,
      "certUrl": "https://mesh.mydomain.site:443"
    }
  }
}
```

with this Caddyfile:

```
mesh.mydomain.site {
    header {
	X-Robots-Tag "none"
	-Server
    }
    reverse_proxy meshcentral:4430
}

```

and this compose.yaml:

```yaml
---
services:
  caddy:
    image: caddy-cloudflare
    restart: always
    env_file:
      - $PWD/.ENV/.caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:z
      - $PWD/site:/srv:z
      - $PWD/caddy_data:/data:z
      - $PWD/caddy_config:/config:z
    networks:
      - caddynet

  meshcentral:
    restart: always
    image: ghcr.io/ylianst/meshcentral:latest
      #    env_file:
      #      - /home/uslugi/.ENV/.mc
    volumes:
      - $PWD/meshcentral/data:/opt/meshcentral/meshcentral-data:z
      - $PWD/meshcentral/user_files:/opt/meshcentral/meshcentral-files:z
      - $PWD/meshcentral/backup:/opt/meshcentral/meshcentral-backups:z
      - $PWD/meshcentral/web:/opt/meshcentral/meshcentral-we:z
    networks:
      - caddynet

networks:
  caddynet:
    name: caddynet
    driver: bridge
...
```
