### DISCUSSION TITLE
Nginx Proxy Manager/Meshcentral issues

### DISCUSSION THREAD

**Discussion by ghxstxch** [Ylianst/MeshCentral#6186] [Issues]
Hi all, 

I apologize for #59409 of this issue, reading around and trying other solutions, none has worked for me. When attempting to reach Meshcentral, I receive a 502 error. Please let me know what other information I can provide, thank you to anyone in advance who can point me in the right direction! 

Here is my docker-compose:

```
version: "3"
networks:
  meshcentral-tier:
    driver: bridge
services:
  mongodb:
    restart: always
    container_name: mongodb
    image: mongo:latest
    env_file:
      - .env
    volumes:
      # mongodb data-directory - A must for data persistence
      - ${STRG_PATH}/meshcentral/mongodb_data:/data/db
    networks:
      - meshcentral-tier
  meshcentral:
    restart: always
    container_name: meshcentral
    # use the official meshcentral container
    image: ghcr.io/ylianst/meshcentral:latest
    depends_on:
      - mongodb
    ports:
      # MeshCentral will moan and try everything not to use port 80, but you can also use it if you so desire, just change the config.json according to your needs
      - 8086:443
    env_file:
      - .env
    volumes:
      # config.json and other important files live here. A must for data persistence
      - ${STRG_PATH}/meshcentral/data:/opt/meshcentral/meshcentral-data
      - ${STRG_PATH}/meshcentral/user_files:/opt/meshcentral/meshcentral-files
      - ${STRG_PATH}/meshcentral/backup:/opt/meshcentral/meshcentral-backups
      - ${STRG_PATH}/meshcentral/web:/opt/meshcentral/meshcentral-web
    networks:
      - meshcentral-tier
```

config.json:

```
  GNU nano 7.2                                                                             config.json
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": true},
    "mongoDb": "mongodb://user:pass@mongodb:27017",
    "cert": "my.domain.here",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "sessionkey",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": true,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": false
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "minify": true,
      "NewAccounts": true,
      "localSessionRecording": true,
      "_userNameIsEmail": true,
      "certUrl": "https://reverse.proxy.ip"
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}


```
