### DISCUSSION TITLE
Help with a working Authelia OIDC configuration

### DISCUSSION THREAD

**Discussion by Nuuki9** [Ylianst/MeshCentral#6432] [Q&A] [answered]
I'm looking for an OIDC configuration for Authelia. I did have it working at one time, using the more stripped down config. However a coupld of weeks back it stopped, with a `403 Forbidden` error.

This led me to try some different things and to go back to the docs again. Right now here's my MC config:

```
"authStrategies": {
  "oidc": {
    "issuer": {
      "issuer": "https://auth.domain.com",
      "authorization_endpoint": "https://auth.domain.com/api/oidc/authorization",
      "token_endpoint": "https://auth.domain.com/api/oidc/token",
      "end_session_endpoint": "https://auth.domain.com/logout",
      "jwks_uri": "https://auth.domain.com/jwks.json"
    },
    "client": {
        "client_id": "meshcentral",
        "client_secret": <SECRET>,
        "redirect_uri": "https://mesh.domain.com/auth-oidc-callback",
        "post_logout_redirect_uri": "https://auth.domain.com/logout",
        "token_endpoint_auth_method": "client_secret_post",
        "response_types": "authorization_code"
    },
    "custom": {
        "scope": [ "openid", "profile", "email", "groups" ],
        "preset": null
    },
    "groups": {
        "required": ["homelab_admin"],
        "siteadmin": ["homelab_admin"],
        "revokeAdmin": false
    }
  }
}
```

And here's my Authelia client config:

```
- client_id: 'meshcentral'
  client_name: 'MeshCentral'
  client_secret: <SECRET>
  public: false
  authorization_policy: 'all_users'
  require_pkce: true
  pkce_challenge_method: 'S256'
  redirect_uris:
    - https://mesh.domain.com/auth-oidc-callback
  scopes:
    - 'openid'
    - 'profile'
    - 'groups'
    - 'email'
  grant_types:
    - refresh_token
    - authorization_code
  userinfo_signed_response_alg: 'none'
  token_endpoint_auth_method: 'client_secret_post'
```

Sadly no change - same error. Does anyone with a working Authelia config have a config they can share?
