### DISCUSSION TITLE
ERROR: Unable to parse config.json

### DISCUSSION THREAD

**Discussion by Br0kenSilos** [Ylianst/MeshCentral#6658] [Issues] [answered]
I've had my MC running for a couple of years now (docker on Ubuntu 22.04). I upgraded it this morning to version 1.1.36. The upgrade went fine. But I noticed something when I started it up. I started it with "docker compose up -d && docker compose logs -f" so I could monitor for any issues. And then I noticed that although it starts and seems to run just fine, I get about 14 of these notices:

mcentral  | ERROR: Unable to parse /opt/meshcentral/meshcentral-data/config.json.

I have run my json through a validator (jsonlint and vscode) and both seem to think the json is just fine. However, VSCode reports the schema is wrong and unreachable. "Unable to load schema from 'http://info.meshcentral.com/downloads/meshcentral-config-schema.json': getaddrinfo ENOTFOUND info.meshcentral.com."

I have attached my config.json (private data obfuscated). Anyone have any idea what is causing those "Unable to parse"  errors?

[config.json](https://github.com/user-attachments/files/18307540/config.json)

I realize that my system is working as expected but having those errors lets me know that "something" is not quite right and I would love to solve it.

**Comment by si458** [comment]
That schema is an old one and no longer accessible 
You should use the raw github one in the sample config.json in the repo https://github.com/Ylianst/MeshCentral/blob/master/sample-config.json

**Comment by Br0kenSilos** [comment]
Thanks @si458 , I updated to json you provided but it still  shows the following message:

"Unable to parse content from 'https://github.com/Ylianst/MeshCentral/blob/master/sample-config.json': Parse error at offset 6."

And my Meshcentral still gives those "mcentral | ERROR: Unable to parse /opt/meshcentral/meshcentral-data/config.json" on starting MeshCentral up as well.

**Reply by si458** [reply]
no sorry i meant use the sample-config.json as an example,
you can see the schema file is set to
`https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json`

but the as for the `Unable to parse /opt/meshcentral/meshcentral-data/config.json` that just emplies the config.json still isnt set correctly and not a valid json for some reason?

**Comment by Br0kenSilos** [comment]
Ah I see.. Thank you. Yes, I have changed the schema to "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json" and now VSCode no longer reports any problems with the config.json file. However, I do still get 13 of the following error messages when starting up MeshCentral. 

"ERROR: Unable to parse /opt/meshcentral/meshcentral-data/config.json."

But they clearly are not "critical" errors because MC starts and runs and "seems" fine. Its just drives me nuts that something things something is wrong with that file and I can't tell what it is. Is there any easy way to find out what the messages are referring to?

**Reply by si458** [reply]
In theory if u get that message, meshcentral will just crash and keep restarting, it won't run at all...
So the must be another instance running somewhere else possibly?

**Comment by Br0kenSilos** [comment]
I'm not sure how there could be another instance running. Basically as I have been testing this, I run "docker compose stop", make any adjustments to the config.json, (or none at all) then I run docker compose up -d && docker compose logs -f". But it does make me wonder if it is picking up from a previous run somehow. So I will try stopping the container and then rebooting and then starting the container just to see.

**Reply by si458** [reply]
What does ur docker compose file look like? Is it maybe loading the wrong config.json or meshcentral 
-data?

**Comment by Br0kenSilos** [comment]
Its pretty straight forward.

```
services:
    meshcentral:
        restart: unless-stopped
        container_name: mcentral
        image: ghcr.io/ylianst/meshcentral:latest
        ports:
            - 17443:443
        environment:
            - HOSTNAME=mc.example.com
            - REVERSE_PROXY=nginxproxymanager
            - REVERSE_PROXY_TLS_PORT=443
            - IFRAME=false
            - ALLOW_NEW_ACCOUNTS=false
            - WEBRTC=false
            - BACKUPS_PW=SuperSecretPassword
            - BACKUP_INTERVAL=24 
            - BACKUP_KEEP_DAYS=35
        volumes:
            - ./data:/opt/meshcentral/meshcentral-data
            - ./user_files:/opt/meshcentral/meshcentral-files
            - ./backups:/opt/meshcentral/meshcentral-backups/
networks:
  default:
    name: proxiable
    external: true
```
