### DISCUSSION TITLE
Deprecation warning

### DISCUSSION THREAD

**Discussion by DaanSelen** [Ylianst/MeshCentral#6754] [Ideas]
After configuring OIDC:
```
MeshCentral HTTP server running on port 443, alias port 443.
ERR: (node:29) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Can this deprecation be handled?

**Comment by si458** [comment]
You are using an old version of node js. we have already fixed this. Make sure you are running nodejs 22

**Reply by DaanSelen** [reply]
I am running the official Container from: `ghcr.io/ylianst/meshcentral:latest`. So is it there?

**Reply by si458** [reply]
Erm that's weird yes we are using the latest node js there? Can u share config and ill see if i can get it to replicate here, as it might be an old module that's causing this error rather than meshcentral itself

**Reply by DaanSelen** [reply]
```
containers:
      - name: meshcentral
        image: ghcr.io/ylianst/meshcentral:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        volumeMounts:
        - name: meshcentral-config
          mountPath: /opt/meshcentral/meshcentral-data/config.json
          subPath: config.json
        - name: meshcentral-certificate
          mountPath: /opt/meshcentral/meshcentral-data/webserver-cert-public.crt
          subPath: webserver-cert-public.crt
        - name: meshcentral-key
          mountPath: /opt/meshcentral/meshcentral-data/webserver-cert-private.key
          subPath: webserver-cert-private.key
        - name: meshcentral-data
          mountPath: /opt/meshcentral/meshcentral-data
        - name: meshcentral-backups
          mountPath: /opt/meshcentral/meshcentral-backups
        - name: meshcentral-web
          mountPath: /opt/meshcentral/meshcentral-web
```
It's Kubernetes so a bit more complex for a quick-n-dirty.

I specifically got this when configuring OIDC and those libraries had been downloading.
`Installing modules [ 'passport', 'connect-flash', 'openid-client@5.7.1', 'pg@8.13.1' ]`
