### DISCUSSION TITLE
MeshCentral agent shows “local” and does not connect (Docker)

### DISCUSSION THREAD

**Discussion by alndao** [Ylianst/MeshCentral#7033] [General]
Hello,

I’m running MeshCentral in Docker (typhonragewind/meshcentral:mongodb-latest).
The web interface works (https://10.192.167.196:8181), and I set HOSTNAME=10.192.167.196:8181 in my docker-compose.

But when I install the Windows agent downloaded from the web UI, it shows “Server URL: local” and does not connect to the server (the device does not appear in the admin web interface).

How can I get the agent to connect properly to my server?
Thank you!

Aly

**Comment by si458** [comment]
1. you should use our official docker image `ghcr.io/ylianst/meshcentral:latest`
2. HOSTNAME should be a hostname and NO port number
3. HOSTNAME should be a DNS name/record which can be resolved by ALL your devices to your meshcentral server ip address, weather internally or externally

**Comment by alndao** [comment]
Hi, thank you for your answer.

I'm currently testing MeshCentral in a local network (not exposed on the internet), so I don't have any public domain name or DNS record available.
For now, I set the HOSTNAME to my local server IP address.

I am attaching my docker-compose.yml file to this message for your reference.

However, even after restarting the containers and downloading a new agent script, my agents cannot connect to the server.

Is it possible to run MeshCentral in a local network using only a local IP address as HOSTNAME?

Are there any specific settings for local testing without a public DNS?

If not, is there a workaround for this use-case?

Thank you for your help!
```
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - "443:443"   # ou "8181:443" si vraiment tu n'as pas le choix, mais voir point 3
    environment:
      - HOSTNAME=192.168.0.98
      - REVERSE_PROXY=false
      - REVERSE_PROXY_TLS_PORT=443
      - ALLOW_NEW_ACCOUNTS=true
      - NODE_ENV=production
      # autres options...
    volumes:
      - ./meshcentral/data:/opt/meshcentral/meshcentral-data
      - ./meshcentral/files:/opt/meshcentral/meshcentral-files
      - ./meshcentral/backups:/opt/meshcentral/meshcentral-backups
      - meshcentral-web:/opt/meshcentral/meshcentral-web
 ```

**Reply by si458** [reply]
> I'm currently testing MeshCentral in a local network (not exposed on the internet)

ok so in this case for testing internally you can just use an IP address,
but the chances are because you set it up originally with a port its not working correctly
so easiest way to fix this is simple, wipe n start again (delete all data inside the `/meshcentral/data` folder, and restart)

PS: if you want a DNS which works internally for testing, i recommand https://sslip.io/ or https://nip.io/
they basically convert DNS+IP'S to IP addresses
`app-116-203-255-68.nip.io maps to 116.203.255.68`
`www.192-168-0-1.sslip.io maps to  192.168.0.1`

**Comment by alndao** [comment]
Hello,

Thank you for your advice!

I have followed your recommendations, but I am still facing the same issue:

I am running MeshCentral in Docker with the following configuration:

```
meshcentral:
  container_name: meshcentral
  image: ghcr.io/ylianst/meshcentral:latest
  restart: always
  depends_on:
    - mongodb
  ports:
    - "443:443"
  environment:
    - HOSTNAME=192.168.0.98
    - REVERSE_PROXY=false
    - REVERSE_PROXY_TLS_PORT=443
    - ALLOW_NEW_ACCOUNTS=true
    - NODE_ENV=production
  volumes:
    - ./meshcentral/data:/opt/meshcentral/meshcentral-data
    - ./meshcentral/files:/opt/meshcentral/meshcentral-files
    - ./meshcentral/backups:/opt/meshcentral/meshcentral-backups
    - meshcentral-web:/opt/meshcentral/meshcentral-web
```
I completely wiped the meshcentral-data folder before restarting the stack, as recommended.

I generated a new agent after setting the HOSTNAME to my local IP (192.168.0.98).

However, the Windows agent still shows "Server URL: local" and does not connect to the server. The device never appears in the admin interface.

Questions:

Is there any other setting I need to adjust to allow agent connections in a local LAN setup?

Is it necessary to regenerate certificates or manually edit the MeshCentral config if I change the HOSTNAME or IP?

Is there any way to check or debug what the agent is actually trying to connect to (e.g., log files)?

Additionally, based on the docker-compose file I shared above, do you see anything that could prevent MeshCentral from working correctly or stop the agents from connecting?
Is there a common mistake or a pitfall in this type of setup that I might have missed?

Thank you very much for your help!
Aly
