### DISCUSSION TITLE
NGINX proxy not working as expected

### DISCUSSION THREAD

**Discussion by huntson** [Ylianst/MeshCentral#7106] [Issues] [answered]
I have a MeshCentral installation that I can use without issue when the clients are pointing directly to the installation via IP.  I am trying to put this behind a reverse proxy to allow for users on the web to get to my service.  Right now I'm just using a reverse proxy locally but I'm not having any luck. 

I watched this video: [https://www.youtube.com/watch?v=ebDVAsistbk](https://www.youtube.com/watch?v=ebDVAsistbk) and took what I thought was the pertinent information.  I did not change the alias port as recommended as my understanding is that the NGINX proxy shoudl take care of this?   I am able to access the mesh central GUI however none of my hosts are able to connect when the agent is installed.  

The hostname below has been purposefully obfuscated. 

Here is my docker compose:

```
version: '3'
services:
    meshcentral:
        restart: always
        container_name: meshcentral
        image: typhonragewind/meshcentral:latest
        ports:
            - 6050:443
        environment:
            - HOSTNAME=meshcentral.xxxxxxx.com
            - REVERSE_PROXY=false
            - REVERSE_PROXY_TLS_PORT=
            - IFRAME=false
            - ALLOW_NEW_ACCOUNTS=true
            - WEBRTC=false
            - BACKUPS_PW=MyAwesomePasswordPleaseChangeMe
            - BACKUP_INTERVAL=24
            - BACKUP_KEEP_DAYS=10
            - TLSOffload = 127.0.0.1

        volumes:
          <insert volumes here>
```

Below are screenshots from my NGINX config.  I'm using Nginx Proxy Manager for this.

[
<img width="519" alt="Screenshot 2025-06-14 at 11 11 35 AM" src="https://github.com/user-attachments/assets/b2fd6894-8ce5-4499-88d9-2a56a755fca3" />
<img width="545" alt="Screenshot 2025-06-14 at 11 11 29 AM" src="https://github.com/user-attachments/assets/2efc5ca4-fb3d-4706-8f4f-f0c4d6525582" />
](url)
