### ISSUE TITLE
Custom path for config.json

### ISSUE THREAD

**Issue by luckydonald** [Ylianst/MeshCentral#160]
Hey, I can't figure out how to specify which file to use for the settings.

I need to load a settings file with is in a different directory as the data directory, as in the docker build the data folder is persistent, but the settings should be coming from the docker image.

If a volume is set to persist a path in docker on volume creation everything will be copied into that storage volume. However if the docker image change, i.e. with a updated `config.json` that change will not overwrite the existing file.

<hr>

For future reference, here my docker configuration:

<details>
<summary><code>Dockerfile </code></summary>

```Dockerfile
# Build argument for image
ARG NODE_VERSION=11.7.0
# docker image
FROM node:${NODE_VERSION}-alpine
# copy build args into environments for easier inspection.
ENV NODE_VERSION ${NODE_VERSION}

# Build argument for mesh central
ARG MESHCENTRAL_VERSION=0.3.1-q
ENV MESHCENTRAL_VERSION ${MESHCENTRAL_VERSION}

ENV MESHCENTRAL_PATH /opt/meshcentral
ENV NODEMODULES_PATH ${MESHCENTRAL_PATH}/node_modules

RUN mkdir -p ${MESHCENTRAL_PATH} \
    && cd ${MESHCENTRAL_PATH} \
    && npm install meshcentral@${MESHCENTRAL_VERSION}

COPY ./config.json ${MESHCENTRAL_PATH}/meshcentral-data/

ENTRYPOINT ["node", "/opt/meshcentral/node_modules/meshcentral/meshcentral"]
```

</details>
<details>
<summary><code>docker-compose.yml</code></summary>

```yml
version: '2.1'

services:
  meshcentral:
    build: ./
    volumes:
        - /data/meshcentral/data:/opt/meshcentral/meshcentral-data
        - /data/meshcentral/files:/opt/meshcentral/meshcentral-files
    ports:
      - 80:80
```

</details>
