### ISSUE TITLE
Login Tokens don't seem to work together with LDAP Auth

### ISSUE THREAD

**Issue by sebthom** [Ylianst/MeshCentral#2773]
I created a login token (the username is something like `~t:Gqy6aAnvP7eUcFRa`. when I try to use it I only get this:
![image](https://user-images.githubusercontent.com/426959/121954618-43528200-cd5f-11eb-945f-b0bca7e119ed.png)

The relevant config part looks something like this:
```yaml
{
    "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
    "settings": {
        "allowLoginToken": true
    },
    "domains": {
        "": {
            "newAccounts": false,
            "userNameIsEmail": false,
            "auth": "ldap",
            "ldapUserName": "uid",
            "ldapUserKey": "dn",
            "ldapOptions": {
                "url": "ldap://<REMOVED>",
                "bindDN": "<REMOVED>",
                "bindCredentials": "<REMOVED>",
                "bindProperty": "dn",
                "searchBase": "<REMOVED>",
                "searchFilter": "(&(uid={{username}})(objectClass=organizationalPerson))"
            },
            "passwordRequirements": {
                "force2factor": true,
                "loginTokens": true
            }
        }
    }
}
```

There is no error reported in the server's error log but this event in the event log:
![image](https://user-images.githubusercontent.com/426959/121955561-66316600-cd60-11eb-9103-5073c8710037.png)
