### ISSUE TITLE
Question about config issue with port 

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#4438]
**Describe your issue**
Hi Currently trying to install the docker version of meshcentral but im having issue with the ports 
on my docker compose i have published http port 8085 and also on the config but it keeps showing error connection  

**Server Software (please complete the following information):**
 - OS:ubuntu
 - Virtualization: docker
 - Network: LAN only then use reverse proxy to expose 

**Your config.json file**
```
{
   "__comment__":"This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
   "settings":{
      "Cert":"remoto.domain.com",
      "mongoDb":"mongodb://meshcentral-db:27017",
      "mongoDbName":"meshcentral",
      "dbEncryptKey":"MyReallySecretPassword2",
      "LANonly":true,
      "Port":8086,
      "RedirPort": 8085,
      "AgentPing":60,
      "AgentPong":60,
      "BrowserPong":20,
      "ignoreagenthashcheck":false
   },
   "domains":{
      "":{
         "Title":"Remoto",
         "Title2":"Remoto",
         "CertUrl":"https://remoto.domain.com:443/"
      }
   }
}
```
log outcome

```
meshcentral-db    | 2022-08-23T08:59:09.252-0500 I NETWORK  [conn7] end connection 172.26.0.2:33508 (10 connections now open)
meshcentral-db    | 2022-08-23T08:59:09.253-0500 I NETWORK  [conn9] end connection 172.26.0.2:33512 (9 connections now open)
meshcentral-db    | 2022-08-23T08:59:09.253-0500 I NETWORK  [conn6] end connection 172.26.0.2:33506 (8 connections now open)
meshcentral-db    | 2022-08-23T08:59:09.254-0500 I NETWORK  [conn10] end connection 172.26.0.2:33514 (7 connections now open)
meshcentral-db    | 2022-08-23T08:59:09.255-0500 I NETWORK  [conn8] end connection 172.26.0.2:33510 (6 connections now open)
meshcentral       | MeshCentral HTTP redirection server running on port 8085.
meshcentral       | MeshCentral v1.0.72, LAN mode.
meshcentral       | Code signed agent MeshService64.exe.
meshcentral       | Code signed agent MeshService.exe.
meshcentral       | MeshCentral HTTPS server running on port 8086.
```
thank you

my docker compose

```
version: '2'
# This is example 2 from the documentation
services:
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/gurucomputing/meshcentral-docker:latest
    restart: "always"
    volumes:
      - meshcentral-data:/meshcentral/meshcentral-data
      - meshcentral-files:/meshcentral/meshcentral-files
      - meshcentral-backup:/meshcentral/meshcentral-backup
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGODB_URL=mongodb://meshcentral-db:27017
      - MONGODB_NAME=meshcentral
      - DB_ENCRYPT_KEY=${DB_ENCRYPT_KEY}
    ports:
      - 8085:8085
      - 8086:8086
    networks:
      - meshcentral-nw
  meshcentral-db:
    container_name: meshcentral-db
    image: mongo:3.6.3
    restart: "always"
    volumes:
      - mongo-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    networks:
      - meshcentral-nw

networks:
  meshcentral-nw:

volumes:
  mongo-data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/mongo-data
  meshcentral-data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/meshcentral-data
  meshcentral-files:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/meshcentral-files
  meshcentral-backup:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/meshcentral-backup
```
Thank you
