### ISSUE TITLE
Multiplatform Docker Image (amd64 and arm64)

### ISSUE THREAD

**Issue by aleuffre** [Ylianst/MeshCentral#4737]
Hello!

Thanks for your hard work on this very useful tool.

I saw you provide a docker image, but it's only for the amd64 architecture. I am deploying MeshCentral on an arm64 machine (as I'm sure many others do, mostly due to lower costs on most cloud providers) and currently I have to rebuild the image myself for arm64. 

You're already using buildx in github actions, so it should be as simple as adding a single line at the end of https://github.com/Ylianst/MeshCentral/blob/master/.github/workflows/docker.yml

```yml
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |              
            INCLUDE_MONGODBTOOLS=true
            PREINSTALL_LIBS=true
```

[Docker documentation](https://docs.docker.com/build/ci/github-actions/examples/#multi-platform-images).

Buildx will build for both architectures in parallel and upload both images under the same tag. The manifest will tell clients which one to download depending on the architecture being targeted.

I think it'd be a very useful feature with very little effort on your part.

Thanks!
