### ISSUE TITLE
Asking for help: Using docker and nginxproxy

### ISSUE THREAD

**Issue by ontheair81** [Ylianst/MeshCentral#5072]
**Describe your issue**
The web browser shows a redirection error when trying to access MeshCentral.

I use dockerized MeshCentral (`typhonragewind/meshcentral`) behind a local reverse proxy consisting of dockerized nginx-proxy (`nginxproxy/nginx-proxy`) with acme-companion (`nginxproxy/acme-companion`).

The reverse proxy runs fine with other containers (Nextcloud, TT-RSS, nginx, and many more). So I am pretty sure I misconfigured the setup of MeshCentral; any help is very appreciated!

**Server Software (please complete the following information):**
 - OS: Debian 11.6
 - Virtualization: Docker
 - Network: KVM-VPS on WAN, reverse proxy on this server (as mentioned above)
 - Version: 1.1.4
 - Node: not sure...?

**Client Device (please complete the following information):**
 - Device: Desktop PC
 - OS: Linux Mint 21.1
 - Network: Remote over WAN
 - Browser: Firefox

**Your docker-compose.yml**
Please note that I commented out some lines as these are - in my understanding - present already in the `config.json`.
```
version: '3'
services:
    meshcentral:
        restart: unless-stopped
        container_name: meshcentral
        image: typhonragewind/meshcentral:1.1.4
        ports:
            - 8086:443
        environment:
            - HOSTNAME=mysub.domain.de 
#           - REVERSE_PROXY=false
#           - REVERSE_PROXY_TLS_PORT=443
            - IFRAME=false 
#           - ALLOW_NEW_ACCOUNTS=true 
#           - WEBRTC=false 
            - VIRTUAL_HOST=mysub.domain.de # Needed by nginxproxy
            - LETSENCRYPT_HOST=mysub.domain.de # Needed by nginxproxy
        volumes:
            - /home/user/bind-mounts/meshcentral/data:/opt/meshcentral/meshcentral-data 
            - /home/user/bind-mounts/meshcentral/user_files:/opt/meshcentral/meshcentral-files 
        networks:
            - "net" # Created by nginxproxy

networks:
  net:
    external: true
```

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mysub.domain.de",
    "_WANonly": true,
    "_LANonly": false,
    "_sessionKey": "[some random string]",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": "172.18.0.2",
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": ""
  },
  "domains": {
        "": {
        "_title": "MyServer",
    "_title2": "Servername",
    "_minify": true,
    "NewAccounts": "",
        "_userNameIsEmail": true,
    "certUrl": "https://mysub.domain.de/:"
        }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
        "production": false
  }
}
```
**Output when starting MeshCentral:**
```
[+] Running 1/1
 ⠿ Container meshcentral  Created                                                                                                                                                                                                       0.1s
Attaching to meshcentral
meshcentral  | Installing otplib@10.2.3...
meshcentral  | MeshCentral HTTP redirection server running on port 80.
meshcentral  | MeshCentral v1.1.4, Hybrid (LAN + WAN) mode, Production mode.
meshcentral  | MeshCentral Intel(R) AMT server running on mysub.domain.de:4433.
meshcentral  | Server has no users, next new account will be site administrator.
meshcentral  | MeshCentral HTTP server running on port 443.
meshcentral  | Loaded web certificate from "https://mysub.domain.de/:", host: "mysub.domain.de"
meshcentral  |   SHA384 cert hash: 92f[shortened]
meshcentral  |   SHA384 key hash: 4b0[shortened]
```

Thank you for any help!
