### ISSUE TITLE
Peering is broken

### ISSUE THREAD

**Issue by rallisf1** [Ylianst/MeshCentral#5373]
**Describe the bug**
Peers cannot connect. Agents connected with 1 peer appear offline in the others.

**To Reproduce**
Setup peering as per https://www.youtube.com/watch?v=j8xIRGScju0
Same data folder and everything. For convenience I use mongodb Atlas. I will change to a local replica when it works.

**dubug -peer**
_server 1_
```
PEER: OutPeer s2: Connecting to: wss://ip.of.server.2:443/meshserver.ashx
PEER: OutPeer s2: Connected
PEER: OutPeer: BAD MESSAGE(A1)
PEER: OutPeer s2: Disconnected
```
_server 2_
```
PEER: InPeer: Connected (ip.of.server.1)
PEER: InPeer: Soft disconnect null (ip.of.server.1)
PEER: InPeer disconnect undefined (ip.of.server.1)
```

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04
 - Virtualization: Docker (official image)
 - Network: WAN, no proxy
 - Version: 1.1.11
 - Node: v18.17.1

**Additional context**
I tried commenting out the ["BAD MESSAGE" check](https://github.com/Ylianst/MeshCentral/blob/04a71800fa4ce94fb75ac480a4562498d17b8fbf/multiserver.js#L104) to see how far it will go but it errors again in the next statement on line 107 with `PEER: OutPeer: Server hash mismatch.`.

I then tried disabling TLS altogether and peering over ws:// but then errored out on line 130 with `PEER: OutPeer: Server sign check failed.`

Something is really wrong with the certificate comparison going on in multiserver.js

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "mongoDb": "mongodb+srv://username:password@mycluster.mongodb.net/?retryWrites=true&w=majority&replicaSet=atlas-dvh64d-shard-0",
    "MongoDbBulkOperations": true,
    "mongoDbChangeStream": true,
    "cert": "my.domain",
    "SessionKey": "SOME_SESSION_KEY",
    "WANonly": true,
    "port": 443,
    "redirPort": 80,
    "AgentPong": 300,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": true,
  },
  "domains": {
    "": {
      "hide": 5,
      "newAccounts": false,
      "userNameIsEmail": true,
      "agentSelfGuestSharing": false
    },
    "my-second.domain": {
      "dns": "my-second.domain",
      "hide": 5,
      "newAccounts": false,
      "userNameIsEmail": true,
      "agentSelfGuestSharing": false
    }
  },
  "peers": {
    "serverId": "s1",
    "servers": {
      "s1": { "url": "wss://server.public.ip:443/" },
      "s2": { "url": "wss://server.public.ip:444/" }
    }
  }
}
```
In the second configuration file the only thing that changes is the `serverId` to `s2` and I use docker port mapping to map the second instance's ports to +1 (81,444,4434).

**Comment by si458** [comment]
Can you share your docker compose at all?

**Comment by rallisf1** [comment]
> Can you share your docker compose at all?

You're right, forgot that.

```yaml
version: '3'

networks:
  meshcentral-tier:
    driver: bridge

services:

  meshcentral:
    restart: always
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 80:80
      - 443:443
      - 4433:4433
    env_file:
      - .env
    volumes:
      - ./data:/opt/meshcentral/meshcentral-data
      - ./meshcentral:/opt/meshcentral/meshcentral
      - ./debug.sh:/opt/meshcentral/startup.sh
    networks:
      - meshcentral-tier

  meshcentral:
    restart: always
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 81:80
      - 441:443
      - 4434:4433
    env_file:
      - .env
    volumes:
      - ./data:/opt/meshcentral/meshcentral-data
      - ./meshcentral:/opt/meshcentral/meshcentral
      - ./debug2.sh:/opt/meshcentral/startup.sh
    networks:
      - meshcentral-tier
```

just added the debug argument in the start up script for s1  (debug.sh)
```sh
#!/bin/bash

if [ -f "meshcentral-data/${CONFIG_FILE}" ]; then
    node meshcentral/meshcentral --configfile "${CONFIG_FILE}" --debug peer
else
    cp config.json.template meshcentral-data/"${CONFIG_FILE}"
    if [ -n "$USE_MONGODB" ] && [ "$USE_MONGODB" == "true" ]; then
        if [ -z "$MONGO_URL" ]; then
            prefix=""
            if [ -n "$MONGO_INITDB_ROOT_USERNAME" ] && [ -n "$MONGO_INITDB_ROOT_PASSWORD" ]; then
                prefix="$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@"
            fi
            MONGO_URL="${prefix}mongodb:27017"
        fi
        sed -i "s/\"_mongoDb\": null/\"mongoDb\": \"mongodb:\/\/$MONGO_URL\"/" meshcentral-data/"${CONFIG_FILE}"
    fi
    sed -i "s/\"cert\": \"myserver.mydomain.com\"/\"cert\": \"$HOSTNAME\"/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"NewAccounts\": true/\"NewAccounts\": $ALLOW_NEW_ACCOUNTS/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"enabled\": false/\"enabled\": $ALLOWPLUGINS/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"localSessionRecording\": false/\"localSessionRecording\": $LOCALSESSIONRECORDING/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"minify\": true/\"minify\": $MINIFY/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"WebRTC\": false/\"WebRTC\": $WEBRTC/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"AllowFraming\": false/\"AllowFraming\": $IFRAME/" meshcentral-data/"${CONFIG_FILE}"
    if [ -z "$SESSION_KEY" ]; then
        SESSION_KEY="$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 48 | head -n 1)"
    fi
    sed -i "s/\"_sessionKey\": \"MyReallySecretPassword1\"/\"sessionKey\": \"$SESSION_KEY\"/" meshcentral-data/"${CONFIG_FILE}"
    if [ "$REVERSE_PROXY" != "false" ]; then
        sed -i "s/\"_certUrl\": \"my\.reverse\.proxy\"/\"certUrl\": \"https:\/\/$REVERSE_PROXY:$REVERSE_PROXY_TLS_PORT\"/" meshcentral-data/"${CONFIG_FILE}"
        node meshcentral/meshcentral --configfile "${CONFIG_FILE}"
        exit
    fi
    node meshcentral/meshcentral --configfile "${CONFIG_FILE}" --cert "$HOSTNAME"
fi
```
and another one for the s2 config (debug2.sh)
```sh
#!/bin/bash

if [ -f "meshcentral-data/${CONFIG_FILE}" ]; then
    node meshcentral/meshcentral --configfile "/opt/meshcentral/meshcentral-data/config2.json" --debug peer
else
    cp config.json.template meshcentral-data/"${CONFIG_FILE}"
    if [ -n "$USE_MONGODB" ] && [ "$USE_MONGODB" == "true" ]; then
        if [ -z "$MONGO_URL" ]; then
            prefix=""
            if [ -n "$MONGO_INITDB_ROOT_USERNAME" ] && [ -n "$MONGO_INITDB_ROOT_PASSWORD" ]; then
                prefix="$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@"
            fi
            MONGO_URL="${prefix}mongodb:27017"
        fi
        sed -i "s/\"_mongoDb\": null/\"mongoDb\": \"mongodb:\/\/$MONGO_URL\"/" meshcentral-data/"${CONFIG_FILE}"
    fi
    sed -i "s/\"cert\": \"myserver.mydomain.com\"/\"cert\": \"$HOSTNAME\"/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"NewAccounts\": true/\"NewAccounts\": $ALLOW_NEW_ACCOUNTS/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"enabled\": false/\"enabled\": $ALLOWPLUGINS/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"localSessionRecording\": false/\"localSessionRecording\": $LOCALSESSIONRECORDING/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"minify\": true/\"minify\": $MINIFY/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"WebRTC\": false/\"WebRTC\": $WEBRTC/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"AllowFraming\": false/\"AllowFraming\": $IFRAME/" meshcentral-data/"${CONFIG_FILE}"
    if [ -z "$SESSION_KEY" ]; then
        SESSION_KEY="$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 48 | head -n 1)"
    fi
    sed -i "s/\"_sessionKey\": \"MyReallySecretPassword1\"/\"sessionKey\": \"$SESSION_KEY\"/" meshcentral-data/"${CONFIG_FILE}"
    if [ "$REVERSE_PROXY" != "false" ]; then
        sed -i "s/\"_certUrl\": \"my\.reverse\.proxy\"/\"certUrl\": \"https:\/\/$REVERSE_PROXY:$REVERSE_PROXY_TLS_PORT\"/" meshcentral-data/"${CONFIG_FILE}"
        node meshcentral/meshcentral --configfile "${CONFIG_FILE}"
        exit
    fi
    node meshcentral/meshcentral --configfile "${CONFIG_FILE}" --cert "$HOSTNAME"
fi
```

**Comment by si458** [comment]
done a PR so you dont have to edit the docker image next time for debug
you will be able to set an environment `ARGS=--debug peer` in the next release!

**Comment by si458** [comment]
i think you are using the same config file on each machine as both 'pods' are using the same value
` - ./data:/opt/meshcentral/meshcentral-data`

so they should be 
`- ./data1:/opt/meshcentral/meshcentral-data`
`- ./data2:/opt/meshcentral/meshcentral-data`

also you havent share ur `.env` file?

**Comment by rallisf1** [comment]
> i think you are using the same config file on each machine as both 'pods' are using the same value ` - ./data:/opt/meshcentral/meshcentral-data`

I change it via the startup script

> also you havent share ur `.env` file?

doesn't matter as I had a config file from the start but here you go

```
NODE_ENV=production

USE_MONGODB=true
# set already exist mongo connection string url here
#MONGO_URL=
# or set following init params for new mongodb, use it with docker-compose file with mongodb version
MONGO_INITDB_ROOT_USERNAME=username
MONGO_INITDB_ROOT_PASSWORD=password

# initial meshcentral-variables
# the following options are only used if no config.json exists in the data-folder

# your hostname
HOSTNAME=my.domain
# set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
REVERSE_PROXY=false
REVERSE_PROXY_TLS_PORT=
# set to true if you wish to enable iframe support
IFRAME=false
# set to false if you want disable self-service creation of new accounts besides the first (admin)
ALLOW_NEW_ACCOUNTS=false
# set to true to enable WebRTC - per documentation it is not officially released with meshcentral and currently experimental. Use with caution
WEBRTC=true
# set to true to allow plugins
ALLOWPLUGINS=false
# set to true to allow session recording
LOCALSESSIONRECORDING=false
# set to enable or disable minification of json, reduces traffic
MINIFY=false
```

**Comment by si458** [comment]
hmmm thanks ill have to have a look when i can, ive never tried peering before?

**Comment by si458** [comment]
just tried it here and it works fine no problems but i used a local mongodb rather than a cloud one
it took some time to setup (mainly mongodb)

docker-compose
```
version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    command: --replSet "rs0"
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081
  meshcentral1:
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 1234:443
    volumes:
      - data:/opt/meshcentral/meshcentral-data
      - user_files:/opt/meshcentral/meshcentral-files
      - backup:/opt/meshcentral/meshcentral-backups
      - web:/opt/meshcentral/meshcentral-web
    environment:
      - HOSTNAME=mc.mytest.com
      - CONFIG_FILE=config.json
  meshcentral2:
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 12345:443
    volumes:
      - data:/opt/meshcentral/meshcentral-data
      - user_files:/opt/meshcentral/meshcentral-files
      - backup:/opt/meshcentral/meshcentral-backups
      - web:/opt/meshcentral/meshcentral-web
    environment:
      - HOSTNAME=mc.mytest.com
      - CONFIG_FILE=config2.json
volumes:
  mongodb:
  data:
  user_files:
  backup:
  web:
```
make sure your STOP both meshcentrals after they start as you need to configure MONGO first

used this url to setup replicaset with just a single server rather than 3
https://www.mongodb.com/docs/manual/tutorial/deploy-replica-set/

i then used mongo-express to create the meshcentral database

config.json (config2.json is IDENTICAL apart from serverId is meshcentral2 rather than meshcentral1)
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "mongoDb": "mongodb://mongo:27017/meshcentral?replicaSet=rs0",
    "mongoDbChangeStream": true,
    "cert": "mc.mytest.com",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "QMCZ8LBNDL8HDQM27EYR85WWNCDOV4R1D1XAVC7ZA7AAS42H",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": false
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "minify": false,
      "NewAccounts": false,
      "localSessionRecording": false,
      "_userNameIsEmail": true,
      "_certUrl": "my.reverse.proxy"
    }
  },
  "peers": {
      "serverId": "meshcentral1",
      "servers": {
          "meshcentral1": {
              "url": "wss://meshcentral1:443/"
          },
          "meshcentral2": {
              "url": "wss://meshcentral2:443/"
          }
      }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}
```

start meshcentral1
setup user and create group
then start meshcentral2
go to url on meshcentral2 and works fine
