### ISSUE TITLE
Meshcentral in Docker on Ubuntu 20.04 not able to update past 1.1.14

### ISSUE THREAD

**Issue by kameleon25** [Ylianst/MeshCentral#5640]
**Describe the bug**
Versions up to and including 1.1.14 worked fine. However after 1.1.15 dropped and the instance tried auto updating it failed with the error: 

`meshcentral  |
meshcentral  |    cd "/opt/meshcentral/meshcentral"
meshcentral  |    npm install --no-audit --no-package-lock --no-optional --omit=optional --no-save meshcentral@1.1.14 archiver@5.3.2 body-parser@1.20.2 cbor@5.2.0 compression@1.7.4 cookie-session@2.0.0 express@4.18.2 express-handlebars@5.3.5 express-ws@4.0.0 ipcheck@0.1.0 minimist@1.2.8 multiparty@4.2.3 @yetzt/nedb node-forge@1.3.1 ua-parser-js@1.0.36 ws@8.14.2 yauzl@2.10.0 nodemailer@6.9.6 otplib@10.2.3
meshcentral  |    node node_modules/meshcentral
meshcentral  | Installing modules...
meshcentral  | ERROR: Unable to install required modules. MeshCentral may not have access to npm, or npm may not have suffisent rights to load the new module. To manualy install this module try:
meshcentral  |`

Version 1.1.16 continues that error.

**To Reproduce**
Change version from 1.1.14 to latest or anything >=1.1.15

**Expected behavior**
I would expect it to update and run. 

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mesh.domain",
    "WANonly": true,
    "_LANonly": true,
    "selfupdate": true,
    "_port": 443,
    "webrtc": true,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "Mesh",
      "title2": "Meshcentral",
      "minify": true,
      "newAccounts": false,
      "certurl": "https://nginxproxy.domain.com:443/",
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
        },

   "smtp": {
    "host": "mail.server",
    "port": 587,
    "from": "email@domain",
    "user": "email@domain",
    "pass": "pass",
    "secure": true
     }

}
```

**Docker-compose.yml**
```
version: '3'

services:
  meshcentral:
    restart: always
    container_name: meshcentral
    # use the official meshcentral container
    image: ghcr.io/ylianst/meshcentral:1.1.16
    mem_limit: 4096m
    mem_reservation: 2048M
    cpus: 1
    ports:
      # MeshCentral will moan and try everything not to use port 80, but you can also use it if you so desire, just change the config.json according to your needs
      - 4895:443
    env_file:
      - .env
    volumes:
      # config.json and other important files live here. A must for data persistence
      - ./meshcentral/data:/opt/meshcentral/meshcentral-data
      # where file uploads for users live
      - ./meshcentral/files:/opt/meshcentral/meshcentral-files
      # location for the meshcentral-backups - this should be mounted to an external storage
      - ./meshcentral/backup:/opt/meshcentral/meshcentral-backups
      # location for site customization files
      - ./meshcentral/web:/opt/meshcentral/meshcentral-web
```

**.env file**
```
NODE_ENV=production

USE_MONGODB=false
# set already exist mongo connection string url here
MONGO_URL=
# or set following init params for new mongodb, use it with docker-compose file with mongodb version
MONGO_INITDB_ROOT_USERNAME=mongodbadmin
MONGO_INITDB_ROOT_PASSWORD=mongodbpasswd

# initial meshcentral-variables
# the following options are only used if no config.json exists in the data-folder

# your hostname
HOSTNAME=mesh.domain
# set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
REVERSE_PROXY=true
REVERSE_PROXY_TLS_PORT=443
# set to true if you wish to enable iframe support
IFRAME=false
# set to false if you want disable self-service creation of new accounts besides the first (admin)
ALLOW_NEW_ACCOUNTS=false
# set to true to enable WebRTC - per documentation it is not officially released with meshcentral and currently experimental. Use with caution
WEBRTC=false
# set to true to allow plugins
ALLOWPLUGINS=false
# set to true to allow session recording
LOCALSESSIONRECORDING=false
# set to enable or disable minification of json, reduces traffic
MINIFY=true
# set this value to add extra arguments to meshcentral on startup (e.g --debug ldap)
ARGS=
```
