### ISSUE TITLE
Linux installer for immutable distros

### ISSUE THREAD

**Issue by Pshemas** [Ylianst/MeshCentral#6163]
It would be great if the Linux installer could recieve a tweak so it would install on immutable distros like Fedora Silverblue, SteamOS etc.

Currently the installer fails during setup - it copies meshagent binary to required location (as ofc not whole drive is non-writable), but fails when creating config file and service file.

If I craete them manually and copy them to intended lcoations the agent (and the service) works as expected.

**Comment by si458** [comment]
https://github.com/Ylianst/MeshCentral/issues/5384

**Comment by tomsik-radek** [comment]
> It would be great if the Linux installer could recieve a tweak so it would install on immutable distros like Fedora Silverblue, SteamOS etc.
> 
> Currently the installer fails during setup - it copies meshagent binary to required location (as ofc not whole drive is non-writable), but fails when creating config file and service file.
> 
> If I craete them manually and copy them to intended lcoations the agent (and the service) works as expected.

Can you please tell me where did you copy the systemd service file? I don't have issues with installing it manually, I just don't know where to put it. As you can see I already tried it in #5384 and it didn't go anywhere

**Comment by bjornfor** [comment]
Bad bot.

**Comment by bjornfor** [comment]
Bad bot.

**Comment by phirestalker** [comment]
For those using ansible, I have a playbook that will do the job.
```
---
- name: Install MeshCentral Agent using the Official Script
  hosts: aurora.local
  become: true
  vars:
    # This is the URL used for the installer script, NOT the direct agent download
    # Example: "https://mesh.yourdomain.com"
    meshcentral_url: "https://mesh.yourdomain.com"

    # This is the token from the install command
    meshcentral_token: "install-id"

  tasks:
    - name: Download MeshCentral Agent Installation Script
      ansible.builtin.get_url:
        url: "{{ meshcentral_url }}/meshagents?script=1"
        dest: /tmp/meshinstall.sh
        mode: '0755'

    - name: Run the official installer (and ignore its expected failure)
      ansible.builtin.command:
        cmd: "/tmp/meshinstall.sh {{ meshcentral_url }} '{{ meshcentral_token }}'"
        chdir: /tmp
      # This is the critical step. We tell Ansible that a failure is OK,
      # because we know the script will fail on the systemd step.
      failed_when: false

    - name: "FIX: Move the generated MSH config file to the correct directory"
      ansible.builtin.copy:
        src: /tmp/meshagent.msh
        dest: /usr/local/mesh_services/meshagent/meshagent.msh
        remote_src: true
        mode: '0644'
      notify: Restart MeshCentral Agent

    - name: Create immutable-friendly systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/meshagent.service
        # The content below points to the files created by the script in their default location.
        content: |
          [Unit]
          Description=MeshCentral Agent

          [Service]
          ExecStart=/usr/local/mesh_services/meshagent/meshagent
          WorkingDirectory=/usr/local/mesh_services/meshagent
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Enable and start the MeshCentral agent service
      ansible.builtin.systemd:
        name: meshagent
        enabled: true
        state: started
        daemon_reload: true

    - name: Clean up installation script
      ansible.builtin.file:
        path: /tmp/meshinstall.sh
        state: absent

  handlers:
    - name: Restart MeshCentral Agent
      ansible.builtin.systemd:
        name: meshagent
        state: restarted
```
I had gemini-cli whip it up for me in only 3 iterations.
