### ISSUE TITLE
Blank page after upgrade from 1.1.24 to 1.1.25

### ISSUE THREAD

**Issue by johann8** [Ylianst/MeshCentral#6271]
**Describe the bug**
Docker image: ghcr.io/ylianst/meshcentral:latest. After the update from 1.1.24 to 1.1.25 you only see a blank page (My Devices) after logging in. On the other tabs some links do not work either. Server console works. You can enter the commands and get a response. If you go back to version 1.1.24, everything works as usual again. I have activated debug mode in the Traefik and Meshcentral container, but could not detect any error messages. Does this have anything to do with the update of `update ws to 8.17.1`?

**To Reproduce**
1. Go to 'Login Page'
2. Click on 'Login'
3. Scroll down to 'My devices'
4. See error: Blank Page

**Expected behavior**
You should see all devices on the “My devices” page

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Rocky Linux 8.10
 - Virtualization: Docker
 - Network: Traefik Reverse proxy
 - Version: 1.1.25
 - Node: v20.12.1

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10/11
 - Network: Remote over WAN
 - Browser: Google Chrome, Mozilla Firefox, Microsoft Edge
 - MeshCentralRouter Version: 

**Remote Device (please complete the following information):**
 - Device: Laptop, Server, VMs
 - OS: Windows 10/11, Debian 12, Rockylinux 8, MS Server 2016/2019
 - Network: Remote over WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**
Traefik Version 3.1.0 - runs on the same host
Docker version 26.1.3

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mc.reduktor.de",
    "WANonly": true,
    "_LANonly": true,
    "_debug": true,
    "sessionKey": "xxxxxxxxxxxxxxxxxx",
    "_CookieEncoding": "hex",
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "RedirAliasPorti": 80,
    "TLSOffload": "traefik",
    "TrustedProxy": "traefik",
    "mongoDb": "mongodb://meshuser:xxxxxxxxxxxxxxxxxx@mongodb:27017/meshcentral",
    "MongoDbName": "meshcentral",
    "Mongodbcol": "meshcentral",
    "MongoDbBulkOperations": true,
    "DbEncryptKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "agentSignLock": true,
    "_AgentPing": 40,
    "AgentPong": 60,
    "_BrowserPing": 40,
    "BrowserPong": 60,
    "AllowHighQualityDesktop": true,
    "desktopMultiplex": true,
    "plugins": {
       "enabled": true
    },
    "WebRTC": true,
    "WebRtcConfig": {
      "iceServers": [
        { "urls": "stun:stun.l.google.com:19302" },
        { "urls": "stun:stun.gmx.de:3478" },
        { "urls": "stun:stun.1und1.de:3478" }
      ]
    },
    "watchDog": { "interval": 100, "timeout": 400 },
    "SelfUpdate": false,
    "nice404": true,
    "clickOnce": true,
    "Compression": true,
    "WsCompression": true,
    "AgentWsCompression": false,
    "NoAgentUpdate": 0,
    "AllowFraming": false,
    "_AllowLoginToken": true,
    "AuthLog": "/opt/meshcentral/meshcentral-data/auth.log",
    "no2FactorAuth": false,
    "Force2Factor": true,
    "CookieIpCheck": true,
    "MaxInvalidLogin": {
       "time": 5,
       "count": 5,
       "coolofftime": 30
    },
    "AutoBackup": {
       "backupIntervalHours": 24,
       "keepLastDaysBackup": 15,
       "backupPath": "/opt/meshcentral/meshcentral-backups"
    },
    "DesktopMultiplexor": true
  },
  "domains": {
        "": {
    "title": "REMOTE SUPPORT PORTAL",
    "title2": "XXXXXX",
    "minify": true,
    "NewAccounts": false,
    "AllowSavingDeviceCredentials": true,
    "scrollToTop": true,
    "nightMode": 0,
    "consentMessages": {
        "consentTimeout" : 30,
        "autoAcceptOnTimeout": true
    },
    "agentCustomization": {
        "_displayName": "MyCompany Agent",
        "_description": "Allows MyCompany to provide full service remote support to this computer.",
        "companyName": "xxxxxxxxxxxx",
        "_serviceName": "MyCompany Remote Support Agent",
        "_fileName": "MyCompanyAgent"
    },
    "_agentConfig": [ "webSocketMaskOverride=1" ],
    "certUrl": "mc.reduktor.de",
    "LoginKey":"HITC94",
    "agentInviteCodes": true,
    "PasswordRequirements": {
       "min": 10,
       "max": 64,
       "upper": 1,
       "lower": 1,
       "numeric": 1,
       "nonalpha": 1,
       "_force2factor": true,
       "skip2factor": "127.0.0.1,172.26.8.0/24"
    },
    "GuestDeviceSharing": {
       "__comment__": "Time in Minutes",
       "maxSessionTime": 240
    },
    "novnc":true,
    "mstsc":true,
    "ssh":true,
    "GeoLocation": true
     }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}
```
#### traefik labels
```yaml
...
  meshcentral:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meshcentral-secure.entrypoints=websecure"
      - "traefik.http.routers.meshcentral-secure.rule=Host(`$HOSTNAME0.$DOMAINNAME`)"
      - "traefik.http.routers.meshcentral-secure.tls=true"
      - "traefik.http.routers.meshcentral-secure.tls.certresolver=production"  # für eigene Zertifikate
      - "traefik.http.routers.meshcentral-secure.service=meshcentral"
      - "traefik.http.services.meshcentral.loadbalancer.server.port=${PORT}"
      - "traefik.http.services.meshcentral.loadbalancer.passHostHeader=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.meshcentral-secure.middlewares=secHeaders@file"
```
#### traefik dynamic_conf.yml
```yaml
...
http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        #frameDeny: true
        # sslRedirect: true                             # deprecated
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: https
...
```
