### ISSUE TITLE
windows 7 no remote destop

### ISSUE THREAD

**Issue by saskuu** [Ylianst/MeshCentral#6580]
**Windows 7 no Remote Desktop**
MeshCentral 1.1.34 (linux debian 12)
client: Windows 7 (6.1.7601)

**To Reproduce**
1. install agent on Windows 7
2. meshcentral (browser)
I see: status: powered. tabs: General, Events, Detail, Console - visible.  tabs: Desktop, Terminal - not visible 
in 5-6 minutes the status of the agent: UnPowered (grey)
3. after reinstalling the agent, everything is repeated
4. all Windows 10-11 - all right 

**Expected behavior**
1. stable connection of the agent 
2. remote destop

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Debian 12
 - Virtualization:  Docker
 - Network: LAN
 - Version: 1.1.34
 - Node: 20.15.1

**Client Device (please complete the following information):**
 - Device: PC
 - OS: LinuxMint
 - Network: LAN
 - Browser: Firefox
 - MeshCentralRouter Version: 

**Remote Device (please complete the following information):**
 - Device: PC
 - OS: Windows 7 (6.1.7601)
 - Network: Lan to Meshcentral, Remote over Lan
 - Current Core Version (if known): Dec 9 2022, 1601542325

**Additional context**
docker-compose.yml
```
version: '3'
services:
  meshcentral:
    restart: unless-stopped # always restart the container unless you stop it
    image: ghcr.io/ylianst/meshcentral:1.1.34 # 1.1.27 is a version number OR use master for the master branch of bug fixes
    ports:
#      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 4433:4433 # AMT (Optional)
    volumes:
      - ./_data/data:/opt/meshcentral/meshcentral-data # config.json and other important files live here
      - ./_data/user_files:/opt/meshcentral/meshcentral-files # where file uploads for users live
      - ./_data/backup:/opt/meshcentral/meshcentral-backups # location for the meshcentral backups - this should be mounted to an external storage
      - ./_data/web:/opt/meshcentral/meshcentral-web # location for site customization files
volumes:
  data:
    driver: local
  user_files:
    driver: local
  backup:
    driver: local
  web:
    driver: local

```
**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "_mongoDb": null,
    "cert": "rd.dom.lcl",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "DD4PS4PCD6DX40SKOCYTN2XLIWBQ7ENIOLBEERQRUD9XHIV5",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": false
  },
  "domains": {
    "": {
      "allowedOrigin": true,
      "_title": "tit",
      "_title2": "tit2",
      "minify": true,
      "NewAccounts": true,
      "localSessionRecording": false,
      "_userNameIsEmail": true,
      "_certUrl": "my.reverse.proxy",
      "SessionRecording": {
        "OnlySelectedDeviceGroups": true,
        "index": true,
        "maxRecordings": 256,
        "maxRecordingSizeMegabytes": 30,
        "filepath": "/opt/meshcentral/meshcentral-backups",
        "protocols": [ 1, 2,  101 ]
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}
```
