### ISSUE TITLE
Issues with external access via reverse proxy (Traefik) after update to 1.1.38

### ISSUE THREAD

**Issue by 3ndexe** [Ylianst/MeshCentral#6796]
**The Problem**
We have been using Meshcentral for quite a while now, but after the update to 1.1.38 a problem has arisen.
As soon as I want to access our Meshcentral instance via the external URL, some things don't work:
- The detail page shows only little information.
- On the general page, the energy status monitoring does not load at all
- Events are missing completely
- Switching monitors is no longer possible during a support connection

We use Traefik V2 as our reverse proxy.
Meshcentral is set so that it can be reached via the internal IP or the host name (https://192.168.x.x:443 or https://hostname.localdomain:443)
The URL with the IP address is then stored in Traefik (https://192.168.x.x:443) and this is then shared externally via https://meshcentral.domain

To summarise, the problems only exist when accessing via https://meshcentral.domain via the internal IP or host name everything works perfectly.
So I assume that I have set something wrong in the config.json of Meshcentral.
But I'm slowly running out of ideas so here I am. :)

**Screenshots**
General page (Internal)
![Image](https://github.com/user-attachments/assets/b855bfec-e70d-47c1-a936-e36698b331bd)
General page (External)
![Image](https://github.com/user-attachments/assets/0ef01ad1-4fd8-484a-af48-08f63c6bc1bc)

Details page (Internal)
![Image](https://github.com/user-attachments/assets/2f9c7048-d4fb-4547-b488-924bd72b08c8)
Details page (External)
![Image](https://github.com/user-attachments/assets/1a4d7b4a-3bb4-4f3b-862d-a174528315e3)

Support (Internal)
![Image](https://github.com/user-attachments/assets/8039721d-b381-4756-8ccf-34886119c7c3)
Support (External)
![Image](https://github.com/user-attachments/assets/a702e9b4-2766-448b-9ad6-9e527a5aeea1)

**Server Software:**
 - OS: Ubuntu 24.04
 - Virtualization: Docker
 - Network: LAN/WAN, reverse proxy (Traefik)
 - Version: 1.1.38
 - Node: v22.11.0

**Additional context**
With the help of Firefox's network analysis, I have discovered an error. As soon as I access the page externally, I see this error. Internally, the commander.ashx file loads correctly.
(Internal)
![Image](https://github.com/user-attachments/assets/0f52da28-9351-4a46-a106-e5acb296aae3)
(External)
![Image](https://github.com/user-attachments/assets/5ac4e8dd-2256-4b8a-be28-1c9b47fb4b36)

**config.json file**
```
{
    "settings": {
        "cert": "<local hostname of the server>",
        "WANonly": true,
        "AllowFraming": true,
        "postgres": {
            "host": "postgres",
            "user": "postgres",
            "port": 5432,
            "password": "********"
        }
    },
    "domains": {
        "": {
            "title": "Company",
            "title2": "MeshCentral",
            "siteStyle": 3,
            "consentMessages": {
                "title": "Fernwartung",
                "desktop": "{0} bittet um Fernzugriff auf den Desktop. Zugang gewähren?",
                "terminal": "{0} bittet um Fernzugriff auf das Terminal. Zugang gewähren?",
                "files": "{0} bittet um Fernzugriff auf Dateien. Zugang gewähren?",
                "consentTimeout": 30,
                "autoAcceptOnTimeout": false,
                "oldStyle": true
            },
            "allowedOrigin": true,
            "AutoRemoveInactiveDevices": 37,
            "agenttag": {
                "ServerName": 1,
                "ServerDesc": 1,
                "ServerTags": 1
            },
            "auth": "ldap",
            "ldapUserGroups": "memberOf",
            "ldapSyncWithUserGroups": true,
            "ldapOptions": {
                "url": "ldap://192.168.x.x.:389",
                "bindDN": "********",
                "bindCredentials": "********",
                "searchBase": "********",
                "searchFilter": "********",
                "reconnect": true
            },
            "ldapUserName": "displayName",
            "ldapUserBinaryKey": "objectGUID",
            "ldapUserEmail": "mail",
            "ldapUserRealname": "name",
            "ldapUserPhoneNumber": "telephoneNumber",
            "noAgentUpdate": 1,
            "passwordRequirements": {
                "force2factor": true
            }
        }
    }
}

```

**Docker Compose file**
```
version: "3.8"

services:
  app:
    image: ghcr.io/ylianst/meshcentral:${MESHCENTRAL_VERSION}
    volumes:
      - /data/meshcentral/data:/opt/meshcentral/meshcentral-data
      - /data/meshcentral/user_files:/opt/meshcentral/meshcentral-files
      - /data/meshcentral/backup:/opt/meshcentral/meshcentral-backups
      - /data/meshcentral/web:/opt/meshcentral/meshcentral-web
    environment:
      _: "${CONFIG_REV}"
    networks:
      - backend
    ports:
      - "443:443"

  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD=**********
    volumes:
      - /data/meshcentral/postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
```

**traefik config**
```
# Meshcentral
[frontends.meshcentral]
backend = "meshcentral"
passHostHeader = true
[frontends.meshcentral.routes.route1]
rule = "Host:meshcentral.domain"
[frontends.meshcentral.headers]
BrowserXSSFilter = true
ContentTypeNosniff = true
ForceSTSHeader = true
FrameDeny = true
STSPreload = true
STSSeconds = 315360000
[backends.meshcentral.servers.server1]
url = "https://192.168.x.x:443"
```
