### ISSUE TITLE
Desktop connection is not usable due to extremely high lag

### ISSUE THREAD

**Issue by vigri** [Ylianst/MeshCentral#6987]
**Describe the bug**
Dear team,
I am testing Meshcentral as a replacement for my current solution. 

I am primarily interested in providing ad-hoc support for my customers.

However, it is almost impossible to operate the computer opposite. The connection either freezes completely or is very delayed.

Sometimes, however, the connection is perfect and works.
Everything is on the local network.

**To Reproduce**
1. Setup MeshCentral using docker
2. get the executable for a Windows Agent or "Assistant"
3. Try to remote control ("Desktop") the computer.
4. You can set the quality to 20% and frame rate to "fastest"
5. Control is almost impossible. Most of the time the "ms" is < 20. Sometimes it jumps up to a couple of seconds (!)

**Expected behavior**
It is clear to me, that MC is not a streaming solution. However, the issue exists even on "plain" windows.

**Screenshots**
Please see the video below.
**Description:** Roughly the first 30 seconds are “okay”. After that, the remote computer can no longer be operated.
https://github.com/user-attachments/assets/a9836685-f898-4515-a653-b46c1f65c59a

**Host**
- OS: Windows 11
- Amd Ryzen 7840U
- 64 GB Memory

Vmware Workstation with two machines:
1) Debian 12 with Docker & Meshcentral (8 Cores, 4GB)
2) Windows 10 (8 Cores, 8GB)

**Server Software (please complete the following information):**
 - OS: Debian 12
 - Virtualization: Docker
 - Network: local
 - Version: 1.0.43
 - Node: 22.13.1

**Client Device (please complete the following information):**
 - Device: Laptop, 7840U, 64GB
 - OS: Windows 11
 - Network: local
 - Browser: Tested with Microsoft Edge and FireFox (137)
 - MeshCentralRouter Version: not used

**Remote Device (please complete the following information):**
 - Device: Virtual machine
 - OS: Windows 10 21H2/19044
 - Network: local
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]
```
PS C:\Users\x\Desktop> .\meshagent64-Group1.exe -info
Compiled on: 18:57:05, Mar  6 2025
   Commit Hash: 28d67274264e140e0c7a4254ad0e32865d5c4a13
   Commit Date: 2025-Mar-6 21:44:07+0000
Using OpenSSL 1.1.1s  1 Nov 2022
Agent ARCHID: 4
Detected OS: Microsoft Windows 10 Pro - 21H2/19044 - x64
```

**Additional context**

Information from the MeshCentral UI:

CPU Load
0.07, 0.05, 0.05

Available Memory
1689.9 Mb free, 3.8 Gb total

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "_mongoDb": null,
    "cert": "mesh.example.com",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "XXXXXXX",
    "port": 443,
    "aliasPort": 8086,
    "redirPort": 80,
    "redirAliasPort": 8081,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": false,
    "webrtc": false
  },
  "domains": {
    "": {
      "title": "MyServer_Title",
      "_title2": "MyServer_Title2",
      "minify": false,
      "NewAccounts": true,
      "localSessionRecording": true,
      "_userNameIsEmail": true,
      "_certUrl": "my.reverse.proxy",
      "AgentInviteCodes": true,
      "allowedOrigin": ["192.168.0.166", "mesh.example.com"]
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}
```

**docker_compose**
```
version: '3'

services:
  meshcentral:
    restart: always
    container_name: meshcentral10
    # use the official meshcentral container
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      # MeshCentral will moan and try everything not to use port 80, but you can also use it if you so desire, just change the config.json according to your needs
      - 8086:443
      - 8081:80
    volumes:
      # config.json and other important files live here. A must for data persistence
      - /home/dockr/container/meshcentral/data:/opt/meshcentral/meshcentral-data
      # where file uploads for users live
      - /home/dockr/container/meshcentral/user_files:/opt/meshcentral/meshcentral-files
      # location for the meshcentral-backups - this should be mounted to an external storage
      - /home/dockr/container/meshcentral/backup:/opt/meshcentral/meshcentral-backups
      # location for site customization files
      - /home/dockr/container/meshcentral/web:/opt/meshcentral/meshcentral-web
```

Please let me know, if you need any further information.
