### ISSUE TITLE
Meshcentral ignores config.json

### ISSUE THREAD

**Issue by Elixir6238** [Ylianst/MeshCentral#7063]
**Describe the bug**
Meshcentral doesn't load the config.json. It  stays in LAN Mode and shows "un-configured" URL

**To Reproduce**
Did a manual install on Ubuntu 24.04.2 cloud image and live image.
Afterwards did new install on Docker with the same behavior

**Expected behavior**
It should start in WAN Mode and use my domain

**Server Software (please complete the following information):**
 - OS: Ubuntu 24.04.2
 - Virtualization: Docker
 - Network: WAN Mode
 - Version: v1.1.45

**Additional context**
Docker compose:
```
version: '3.8'

services:
  meshcentral:
    image: ghcr.io/ylianst/meshcentral:latest # <-- HIER IST DIE ÄNDERUNG!
    container_name: meshcentral
    restart: always
    ports:
      - "8080:8080" # MeshCentral HTTP-Port (intern 8080, extern 8080 - Nginx proxy auf diesen)
      - "443:443"   # Agent-Port (intern 443, extern 443 - wichtig für Agentenkommunikation)
      - "8899:8899" # Peer-to-Peer Port (optional, kann auskommentiert werden, wenn nicht benötigt)
      - "1883:1883" # MQTT-Port (optional, kann auskommentiert werden, wenn nicht benötigt)
    volumes:
      - ./meshcentral-data:/opt/meshcentral/meshcentral-data # Persistentes Datenvolume
      - ./config.json:/opt/meshcentral/meshcentral-data/config.json # Konfigurationsdatei
    environment: {} # Dies ist das leere Mapping, das den Fehler behebt
    # Optional: Wenn Sie Konfigurationsoptionen über Umgebungsvariablen setzen möchten
    # - "MESH_SETTINGS_WANONLY=true"
    # - "MESH_DOMAINS__URL=https://haluki.icu"
    # Wir nutzen hier die config.json über das Volume, was flexibler ist.
```

**Your config.json file**
```
{
  "settings": {
    "WANonly": true,
    "port": 8080,
    "_PeerPort": 8899,
    "MqttPort": 1883,
    "AgentPort": 443,
    "DnsOverride": "meshcentral.haluki.icu",
    "MinAccountPasswordLen": 12,
    "AllowEmailLogin": true,
    "SessionTimeoutMinutes": 60,
    "UserInactivityTimeoutMinutes": 30,
    "TlsOffload": true,
    "debug": true,         
    "debugLogLevel": 100,  
    "debugHttp": true      
  },
  "domains": {
    "": {
      "title": "MeshCentral für meshcentral.haluki.icu",
      "title2": "Remote Access & Management",
      "userfab": "Haluki IT",
      "url": "https://meshcentral.haluki.icu",
      "welcomeText": "Willkommen auf Ihrem MeshCentral Server!",
      "NewAccounts": true,
      "email": {
        "smtp": "smtp.ionos.de",
        "from": "infol@haluki.icu",
        "user": "info@haluki.icu",
        "password": "MyPassword",
        "tls": true
      }
    }
  }
}
```
