### ISSUE TITLE
ERR: (node:30) [MONGODB DRIVER] Warning: no saslprep library specified

### ISSUE THREAD

**Issue by johann8** [Ylianst/MeshCentral#7128]
**Describe the bug**
After updating to version 1.1.46, an error message appears when starting Meshcentral that no saslprep library is specified.

**To Reproduce**
1. Go to '/opt/meshcentral'
2. Run 'docker compose pull'
3. Run 'docker compose down && docker compose up -d'
4. RUN 'docker compose logs meshcentral'
5.  See error
```bash
meshcentral  | Installing modules [ 'nodemailer@6.9.16', 'image-size@2.0.2' ]
meshcentral  | ERR: (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
meshcentral  | (Use `node --trace-warnings ...` to show where the warning was created)
meshcentral  | ERR: (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
meshcentral  | (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
meshcentral  | MeshCentral HTTP redirection server running on port 800.
meshcentral  | MeshCentral v1.1.46, WAN mode, Production mode.
meshcentral  | ERR: (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
meshcentral  | ERR: (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
```

**Expected behavior**
An error message should not appear.

**Screenshots**
None

**Server Software (please complete the following information):**
 - OS: Rocky Linux 8.10
 - Virtualization: Docker
 - Network: LAN/WAN, reverse proxy traefik]
 - Version: 1.1.46
 - Node: 22.15.1

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Network: Remote over WAN
 - Browser: Firefox
 - MeshCentralRouter Version: 

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11 24H2
 - Network: Remote over WAN
 - Current Core Version (if known): Mar 6 2025, 300182293

**Additional context**
1. run 'docker compose exec meshcentral bash'
2.  run 'ce0c094290eb:/opt/meshcentral# node --trace-warnings .'
```bash
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module '/opt/meshcentral'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.15.1
```

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mc.redacted.de",
    "WANonly": true,
    "_LANonly": true,
    "SessionKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "_CookieEncoding": "hex",
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "RedirAliasPort": 80,
    "TLSOffload": "traefik",
    "TrustedProxy": "traefik",
    "_MaintenanceMode": true,
    "mongoDb": "mongodb://meshuser:xxxxxxxxxxxxxxxxxxxxxxxxxx@mongodb:27017/meshcentral",
    "MongoDbName": "meshcentral",
    "Mongodbcol": "meshcentral",
    "MongoDbBulkOperations": true,
    "DbEncryptKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "_MongoDbChangeStream": true,
    "_AgentPing": 60,
    "AgentPong": 60,
    "_BrowserPing": 60,
    "BrowserPong": 60,
    "_agentIdleTimeout": 150,
    "_agentSignLock": true,
    "AllowHighQualityDesktop": true,
    "WebRTC": true,
    "WebRtcConfig": {
      "iceServers": [
        { "urls": "stun:stun.l.google.com:19302" },
        { "urls": "stun:stun.gmx.de:3478" },
        { "urls": "stun:stun.1und1.de:3478" }
      ]
    },
    "watchDog": { "interval": 100, "timeout": 400 },
    "SelfUpdate": false,
    "nice404": true,
    "Compression": true,
    "WsCompression": true,
    "AgentWsCompression": false,
    "NoAgentUpdate": 0,
    "AllowFraming": "false",
    "_AllowLoginToken": true,
    "AuthLog": "/opt/meshcentral/meshcentral-data/auth.log",
    "no2FactorAuth": false,
    "CookieIpCheck": true,
    "MaxInvalidLogin": {
       "time": 5,
       "count": 5,
       "coolofftime": 30
    },
    "AutoBackup": {
       "backupIntervalHours": 24,
       "keepLastDaysBackup": 15,
       "backupPath": "/opt/meshcentral/meshcentral-backups"
    },
    "plugins": {
         "enabled": false
    },
    "DesktopMultiplex": true
  },
  "domains": {
        "": {
    "title": "REMOTE SUPPORT PORTAL",
    "title2": "WG",
    "NewAccounts": false,
    "AllowSavingDeviceCredentials": true,
    "scrollToTop": true,
    "showModernUIToggle": true,
    "_force everyone to use the new modern style and let them also pick a custom color theme ": false,
    "_siteStyle:": 3,
    "nightMode": 0,
    "welcomeText": "<a href='https://redacted.de/' target='_blank' style='text-decoration: none;'>redacted</a> - SUPPORT PORTAL",
    "Footer": "<a href='https://redacted.de/' target='_blank' style='text-decoration: none;'>redacted</a> - SUPPORT PORTAL",
    "_welcomePicture": "sdc.jpg",
    "consentMessages": {
        "consentTimeout" : 30,
        "autoAcceptOnTimeout": true
    },
    "agentCustomization": {
        "displayName": "MeshCentral Agent XXX",
        "_description": "Allows MyCompany to provide full service remote support to this computer.",
        "companyName": "XXXXXXX XXXXXXXXX GmbH",
        "_serviceName": "WKT Remote Support Agent",
        "_fileName": "MyCompanyAgent"
    },
    "agentConfig": [ "webSocketMaskOverride=1" ],
    "certUrl": "mc.redacted.de",
    "LoginKey":"XXXXXX",
    "agentInviteCodes": true,
    "assistantTypeAgentInvite": 3,
    "PasswordRequirements": {
       "min": 10,
       "max": 64,
       "upper": 1,
       "lower": 1,
       "numeric": 1,
       "nonalpha": 1,
       "_backupcode2factor": true,
       "single2factorWarning": false,
       "Force2Factor": true,
       "skip2factor": "127.0.0.1,172.26.0.0/24"
    },
    "terminal": {
       "linuxshell": "any",
       "launchCommand": {
          "linux": "cd /tmp\nclear\necho \"Hello Linux\"\n",
          "_darwin": "clear\necho \"Hello MacOS\"\n",
          "_freebsd": "clear\necho \"Hello FreeBSD\"\n"
       }
    },
    "_userNameIsEmail": true,
    "_ManageAllDeviceGroups":["j.xxxxx@redacted.de"],
    "_IpBlockedUserRedirect": "https://www.microsoft.com",
    "GuestDeviceSharing": {
          "__comment__": "Time in Minutes",
          "maxSessionTime": 240
      },
    "novnc":true,
    "mstsc":true,
    "ssh":true,
    "GeoLocation": true
     }
  },
  "_letsencrypt": {
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  },
  "smtp": {
    "host": "mx01.redacted.de",
    "port": 587,
    "from": "meshcentral@redacted.de",
    "user": "meshcentral@redacted.de",
    "pass": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "tls": false
   }
}
```

**Comment by si458** [comment]
does the container start up ok?
as from my understanding the mongodb module includes a saslprep module now
which is why we removed it?

**Comment by johann8** [comment]
Thank you for the quick reply!
Yes, the container starts normally and Meshcentral works without errors. I could not detect any errors in the function. 
I have also stopped the container, deleted the Docker image and reloaded it. 
The error remains. 
I use the Docker image ghcr.io/ylianst/meshcentral:latest and MongoDB version 7. 
Best regards

**Comment by si458** [comment]
Yeh we removed the sawlprep module because it was included in the newer mongodb npm modules?
Maybe I was mistaken!
I will look into it when I get chance but nothing to panic about! It's just a warning rather than an error from my understanding

**Comment by DaanSelen** [comment]
> Yeh we removed the sawlprep module because it was included in the newer mongodb npm modules? Maybe I was mistaken! I will look into it when I get chance but nothing to panic about! It's just a warning rather than an error from my understanding

Hopefully its not Docker!

**Comment by si458** [comment]
is this still an issue and also can you share your docker-compose.yaml if so

**Comment by johann8** [comment]
Hi,
yes, when the Docker container starts, I still see the error. However, the function is not affected.
```
meshcentral  | Tue Aug 26 15:36:18 CEST 2025
meshcentral  | Config file: /opt/meshcentral/meshcentral-data/config.json
meshcentral  | Pre-existing config found, not recreating...
meshcentral  | Leaving config as-is.
meshcentral  | Installing modules [ 'nodemailer@6.9.16', 'image-size@2.0.2' ]
meshcentral  | ERR: (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
meshcentral  | (Use `node --trace-warnings ...` to show where the warning was created)
meshcentral  | ERR: (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
meshcentral  | ERR: (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
meshcentral  | MeshCentral HTTP redirection server running on port 800.
meshcentral  | MeshCentral v1.1.48, WAN mode, Production mode.
meshcentral  | ERR: (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
meshcentral  | ERR: (node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
meshcentral  | MeshCentral Intel(R) AMT server running on mc.xxxxxxxxx.de:4433.
meshcentral  | MeshCentral HTTP server running on port 4430, alias port 443.
```
Below is my configuration:
- docker-compose.yml
```
---
networks:
  meshcentralNet:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}.0/24

services:
  # meshcentral container
  meshcentral:
    restart: always
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:${MC_VERSION}
    environment:
      - TZ=${TZ}
      - HOSTNAME=${HOSTNAME_MC}
      - REVERSE_PROXY=${REVERSE_PROXY}
      - REVERSE_PROXY_TLS_PORT=${REVERSE_PROXY_TLS_PORT}
      - NODE_ENV=${NODE_ENV}
      - USE_TRAEFIK=${USE_TRAEFIK}
      - PORT=${PORT}
      - USE_MONGODB=${USE_MONGODB}
      - MONGO_URL=${MONGO_URL}
      - IFRAME=${IFRAME}
      - ALLOW_NEW_ACCOUNTS=${ALLOW_NEW_ACCOUNTS}
      - WEBRTC=${WEBRTC}
      - LOCALSESSIONRECORDING=${LOCALSESSIONRECORDING}
      - MINIFY=${MINIFY}
    volumes:
      - "${DOCKERDIR}/data/mc/data:/opt/meshcentral/meshcentral-data"
      - "${DOCKERDIR}/data/mc/user_files:/opt/meshcentral/meshcentral-files"
      - "${DOCKERDIR}/data/mc/backups:/opt/meshcentral/meshcentral-backups"
      - "${DOCKERDIR}/data/mc/web:/opt/meshcentral/meshcentral-web"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - meshcentralNet

  # mongodb container for
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: "always"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "${DOCKERDIR}/data/mongodb/dbdata:/data/db"
      - "${DOCKERDIR}/data/mongodb/dbbackup:/data/dbbackup"
    env_file:
      - .env
    #network_mode: none
    networks:
      - meshcentralNet
```
- docker-compose.override.yml
```
---
services:

  meshcentral:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      ### ==== to routers ====
      - "traefik.http.routers.meshcentral-secure.entrypoints=websecure"
      - "traefik.http.routers.meshcentral-secure.rule=Host(`$HOSTNAME0.$DOMAINNAME`)"
      - "traefik.http.routers.meshcentral-secure.tls=true"
      - "traefik.http.routers.meshcentral-secure.tls.certresolver=production"         # für eigene Zertifikate
      - "traefik.http.routers.meshcentral-secure.middlewares=secHeaders@file"
      - "traefik.http.routers.meshcentral-secure.service=meshcentral"
      ### ==== to service ====
      - "traefik.http.services.meshcentral.loadbalancer.server.port=${PORT}"
      - "traefik.http.services.meshcentral.loadbalancer.passHostHeader=true"
    networks:
      - proxy

networks:
  proxy:
    external: true
```
- .env
```
#
### === SYSTEM ===
#
# your time zone
TZ="Europe/Berlin"
DOCKERDIR=/opt/meshcentral

#
### === Network ===
#
HOSTNAME_MC=mc.xxxxxxx.de
DOMAINNAME=xxxxxxx.de
HOSTNAME0=mc
PORT=4430
SUBNET=172.26.8
REVERSE_PROXY=${HOSTNAME_MC}
REVERSE_PROXY_TLS_PORT=443

#
### === APP Meshcentral ===
#
# Set MeshCentral to Produktion
NODE_ENV=production

# meshcentral version
MC_VERSION=latest
#MC_VERSION=1.1.41

# RP traefik
USE_TRAEFIK="true"

# use mongodb
# generate password: pwgen -1cnsB 25 1
USE_MONGODB=true
MONGO_MC_USERNAME=meshuser
MONGO_MC_USER_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxx
MONGO_DB_NAME=meshcentral

# set already exist mongo connection string url here
MONGO_URL='mongodb://meshuser:xxxxxxxxxxxxxxxxxxxxxxxxxxx@mongodb:27017/meshcentral'

# or set following init params for new mongodb, use it with docker-compose file with mongodb version
# pwgen -1cnsB 30 1
MONGO_INITDB_ROOT_USERNAME=admin
MONGO_INITDB_ROOT_PASSWORD=123xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#set to true if you wish to enable iframe support
IFRAME=false

#set to false if you want disable self-service creation of new accounts besides the first (admin)
ALLOW_NEW_ACCOUNTS=false

#set to true to enable WebRTC - per documentation it is not officially released with meshcentral, but is solid enough to work with. Use with caution
WEBRTC=true

# set to true to allow session recording
LOCALSESSIONRECORDING=false

# set to enable or disable minification of json, reduces traffic
MINIFY=true

#
### === Build Option ===
#
INCLUDE_MONGODB_TOOLS=true
PREINSTALL_LIBS=true
```
Best regards
